swagger: "2.0"
info:
  title: "API Test"
  version: "0.0.1"
paths:
  /endpoint:
    get:
      summary: "Get login info from phone number"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "JWT Token"
        required: true
        type: "string"
      - name: "phone"
        in: "query"
        description: "Phone number"
        required: true
        type: "string"
      responses:
        "200":
          description: Validation exception
          schema:
            $ref: "#/definitions/Endpoint200"
        "400":
          description: Invalid phone number
          schema:
            $ref: "#/definitions/Endpoint400"
        "401":
          description: Invalid credential
          schema:
            $ref: "#/definitions/Endpoint401"

definitions:
  Endpoint200:
    type: "object"
    properties:
      status:
        type: "boolean"
        default: true
      user_group_id:
        type: "string"

  Endpoint400:
    type: "object"
    properties:
      status:
        type: "boolean"
        default: false
      reason:
        type: "string"
        default: "Invalid phone number"

  Endpoint401:
    type: "object"
    properties:
      status:
        type: "boolean"
        default: false
      reason:
        type: "string"
        default: "Invalid credential"
      